### ISSUE TITLE
Everyone installs Zenhub plugin

### ISSUE THREAD

**Issue by asyoussef** [internship-team-ny/Planning#1]

**Comment by moazhamza** [comment]
Done

**Comment by nashahzad** [comment]
Done

**Comment by whamza15** [comment]
Done. I added this issue to backlog :)
Learning how to use agile properly now

**Comment by asyoussef** [comment]
Done.
All I had to do is to go to zenhub.com and click the big green button. The rest follows smoothly and boards were magically added to my github.

**Comment by malikh72** [comment]
Done

**Comment by whamza15** [comment]
@mhamza15 please confirm
