### ISSUE TITLE
Basic Knowledge of how to use github

### ISSUE THREAD

**Issue by whamza15** [internship-team-ny/Planning#2]
Our level of knowledge here may vary. We have to make sure we can:

- Access repositories (clone, pull, commit, push, etc.)
- Create new repositories
- Create Issues, assign them, and comment on them, change their status
- Access Zenhub for planning and execution

There are tons of online tutorials that you can google. Choose the one you like. You can always seek help on slack from other team members/mentors

**Comment by whamza15** [comment]
Done

**Comment by moazhamza** [comment]
Done

**Comment by nashahzad** [comment]
Done

**Comment by asyoussef** [comment]
Done
